### PR TITLE
Topic/perl prereqs

### PR DESCRIPTION
**Pull request by karenetheridge**
also get the minimum perl requirement from configure, build and test prereqs, as done for [MakeMaker] in https://github.com/rjbs/Dist-Zilla/pull/318

also inject the MBT version into build-requires, as ./Build uses MBT

(I guess these might technically belong in two separate PRs.. I can split them if you want)

### CODE REVIEW

**Comment by karenetheridge** [comment]
If the perl prereq was being set manually, it would probably be in the runtime section, but lots of things inject requirements into every phase, so it can conceivably happen that another phase is holding the perl prereq, not runtime.

It is more correct to do it this way, at least :)

I will update the PR to not do anything with the build requirements.

**Comment by karenetheridge** [comment]
force-pushed

**Comment by Leont** [comment]
I think the method you're looking for it $prereqs->merged_requirements.

**Comment by karenetheridge** [comment]
> I think the method you're looking for it $prereqs->merged_requirements.

Is that a less-than-direct way of saying "what you're doing is wrong"?  This is the same code as in the dzil core for extracting the perl prereq, and it's faster this way than merging all of the prereqs for the entire distribution together and then extracting just one key.

**Comment by Leont** [comment]
> Is that a less-than-direct way of saying "what you're doing is wrong"?

It's my less than direct way of saying "I'm too lazy to rewrite that into something much shorter."

> it's faster this way than merging all of the prereqs for the entire distribution together and then extracting just one key.

I was under the mistaken impression I was dealing with a CPAN::Meta::Prereqs object instead of a Dist::Zilla::Prereqs one that doesn't do what I expected it to :-/.

**Comment by karenetheridge** [comment]
https://github.com/rjbs/Dist-Zilla/blob/master/lib/Dist/Zilla/Plugin/MakeMaker.pm#L187

**Comment by Leont** [comment]
Merged, with my modification.

**Pull request closed without merging**
